name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.7

  build:
    needs: ruby-versions
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - { os: windows-latest , ruby: mingw }
          - { os: windows-latest , ruby: mswin }
        exclude:
          - { os: windows-latest , ruby: head }
          - { os: windows-latest , ruby: truffleruby }
          - { os: windows-latest , ruby: truffleruby-head }

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
